name: Build and publish API documentation

on:
    push:
        branches: [ "main" ]
    workflow_dispatch:

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3

            -   name: Set up JDK 11
                uses: actions/setup-java@v3
                with:
                    java-version: '11'
                    distribution: 'temurin'

            -   name: Validate Gradle wrapper
                uses: gradle/wrapper-validation-action@v1

            -   name: Build with Gradle
                uses: gradle/gradle-build-action@v2
                with:
                    arguments: build

            -   name: Deploy to GitHub Pages
                if: success()
                uses: crazy-max/ghaction-github-pages@v3
                with:
                    target_branch: gh-pages
                    build_dir: build/docs
                    keep_history: true
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
